rm(list=ls())
delivery <- read.csv("eg3.1.delivery.csv",h=T)
names(delivery)
cor(delivery)
pairs(delivery,pch=20)
model1 <- lm(delivery$DeliveryTime ~ delivery$NumberofCases+delivery$Distance)
model2 <- lm(DeliveryTime ~ NumberofCases+ Distance, data=delivery)

influence.measures(model1)
cooks.distance(model1)
dfbetas(model1)
dffits(model1)
plot(model1)
influence.measures(model1)
